"""teff — workflow as data, agents as graphs.

A Python framework for building AI agent workflows using
graph-based pipelines with built-in tools and RAG support.
"""

from teff import hooks
from teff._version import __version__
from teff.assistant import Assistant
from teff.errors import (
    ConfigError,
    TeffError,
    InterruptError,
    LLMError,
    NodeError,
    WorkflowError,
    redact,
)
from teff.eval import extract_output, load_dataset, run_eval
from teff.flow import Case, Flow, SubFlow
from teff.graph import Edge, Graph, TurnResult
from teff.harness import Harness
from teff.logging import (
    configure_logging,
    get_logger,
    new_run_id,
    run_id,
)
from teff.memory import (
    MemoryConfig,
    MemoryExtractor,
    MemoryItem,
    MemoryStore,
    MemoryTool,
    last_user_text,
    memory_context,
    memory_context_from_config,
)
from teff.node import (
    LLM,
    Command,
    ExecContext,
    GraphInterrupt,
    Interrupt,
    Map,
    Node,
    NodeRegistry,
    Parallel,
    ReActAgent,
    Retry,
    StructuredOutputError,
    ToolExec,
    Transform,
    default_registry,
    node,
)
from teff.provider import (
    BUILTINS,
    DEFAULT_PROVIDERS,
    Provider,
    ProviderRegistry,
    provider_concurrency,
    set_provider_concurrency,
    to_provider_registry,
    validate_provider_refs,
)
from teff.rag import Chunker, Embedder, ImageTool, PDFTool, RAGTool, VectorStore
from teff.rag.stores import (
    ChromaVectorStore,
    InMemoryVectorStore,
    PGVectorStore,
    QdrantVectorStore,
)
from teff.schema import json_schema_from_type, validate_json
from teff.skill import Skill, core_skills, get_core_skill, load_skill
from teff.state import (
    Reducer,
    State,
    apply_reducers,
    reducers_from_typeddict,
    reducers_from_yaml_schema,
    state_schema_to_jsonschema,
    validate_state,
)
from teff.stream import StreamEvent
from teff.tool import Tool, ToolRegistry, default_tool_registry, tool
from teff.trace import (
    RunSummary,
    RunTracer,
    TokenUsage,
    TraceEvent,
    clear_pricing,
    load_pricing,
    model_pricing,
    set_model_pricing,
    set_provider_pricing,
    tokens_cost,
)
from teff.yaml import from_yaml
from teff.yaml_schema import validate_workflow, validate_workflow_file

__all__ = [
    "__version__",
    "Assistant",
    "hooks",
    "TurnResult",
    "configure_logging",
    "get_logger",
    "run_id",
    "new_run_id",
    "TeffError",
    "ConfigError",
    "WorkflowError",
    "NodeError",
    "LLMError",
    "InterruptError",
    "redact",
    "Node",
    "NodeRegistry",
    "default_registry",
    "ExecContext",
    "node",
    "Retry",
    "Tool",
    "ToolRegistry",
    "default_tool_registry",
    "tool",
    "Graph",
    "Edge",
    "Transform",
    "LLM",
    "StructuredOutputError",
    "ReActAgent",
    "ToolExec",
    "Parallel",
    "Map",
    "Interrupt",
    "GraphInterrupt",
    "Command",
    "Flow",
    "Case",
    "SubFlow",
    "Harness",
    "set_provider_concurrency",
    "provider_concurrency",
    "Skill",
    "load_skill",
    "core_skills",
    "get_core_skill",
    "json_schema_from_type",
    "validate_json",
    "VectorStore",
    "Embedder",
    "Chunker",
    "RAGTool",
    "PDFTool",
    "ImageTool",
    "MemoryStore",
    "MemoryItem",
    "MemoryTool",
    "MemoryExtractor",
    "MemoryConfig",
    "memory_context",
    "memory_context_from_config",
    "last_user_text",
    "InMemoryVectorStore",
    "QdrantVectorStore",
    "ChromaVectorStore",
    "PGVectorStore",
    "from_yaml",
    "State",
    "reducers_from_typeddict",
    "reducers_from_yaml_schema",
    "state_schema_to_jsonschema",
    "validate_state",
    "apply_reducers",
    "Reducer",
    "RunTracer",
    "TraceEvent",
    "RunSummary",
    "TokenUsage",
    "model_pricing",
    "tokens_cost",
    "set_model_pricing",
    "set_provider_pricing",
    "load_pricing",
    "clear_pricing",
    "validate_workflow",
    "validate_workflow_file",
    "run_eval",
    "load_dataset",
    "extract_output",
    "StreamEvent",
    "Provider",
    "ProviderRegistry",
    "DEFAULT_PROVIDERS",
    "BUILTINS",
    "to_provider_registry",
    "validate_provider_refs",
]
